spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: ${SCHEMA_NAME}
        format_sql: true
    show-sql: true
base62:
  charset: ${BASE_62}

aws:
  access_key: ${USERNAME}
  private_key: ${PRIVATE_KEY}

jwt:
  secret:
    key: 33b~OExIB6Td><!*LKHyqB5[kK:L9_Z&Ytx8#sWi2^PD7":RnprWA.3I`W-cw]K