spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

sms:
  api:
    key: ${SMS_KEY}
    secret: ${SMS_SECRET}
  sender: ${SMS_SENDER}

cloud:
  aws:
    region:
      static: ${OBJECT_REGION}
    credentials:
      access-key: ${OBJECT_ACCESS}
      secret-key: ${OBJECT_SECRET}
    s3:
      bucket: ${BUCKET_NAME}

google:
  calendar:
    calendar-id: ${CALENDAR_ID}
    application-name: ${APPLICATION_NAME}
    attendee-email: ${ATTENDEE_EMAIL}
    service-account-key-base64: ${SERVICE_ACCOUNT_KEY_BASE64}

jwt:
  secret:
    key: ${JWT_SECRET}