spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: ${SCHEMA_NAME}
        format_sql: true
    show-sql: true
base62:
  charset: ${BASE_62}

sms:
  api:
    key: ${SMS_KEY}
    secret: ${SMS_SECRET}
  sender: ${SMS_SENDER}

jwt:
  secret:
    key: ${JWT_SECRET}