name: Deploy to NCP VM

on:
  push:
    branches: [ main ]

env:
  RESOURCE_PATH: ./src/main/resources/application.yml

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set yml file
        uses: microsoft/variable-substitution@v1
        with:
          files: ${{ env.RESOURCE_PATH }}
        env:
          spring.datasource.url: ${{ secrets.TEST }}
          spring.datasource.username: ${{ secrets.DB_USER }}
          spring.datasource.password: ${{ secrets.DB_PASSWORD }}

      - name: Debug - Check file existence
        run: |
          echo "test: ${{ secrets.TEST }}"

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/app
            git pull origin main
            ./gradlew bootJar
            pkill -f 'java -jar' || true
            nohup java -jar build/libs/*.jar > app.log 2>&1 &