name: Docker CI/CD to EC2

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_APP }}:latest

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cat <<EOF > /home/ec2-user/app/.env
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_URL=${{ secrets.DB_URL }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            SMS_KEY=${{ secrets.SMS_KEY }}
            SMS_SECRET=${{ secrets.SMS_SECRET }}
            SMS_SENDER=${{ secrets.SMS_SENDER }}
            BUCKET_NAME=${{ secrets.BUCKET_NAME }}
            OBJECT_ACCESS=${{ secrets.OBJECT_ACCESS }}
            OBJECT_REGION=${{ secrets.OBJECT_REGION }}
            OBJECT_SECRET=${{ secrets.OBJECT_SECRET }}
            EOF
  
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_APP }}:latest
            docker stop ${{ secrets.DOCKERHUB_APP }} || true
            docker rm ${{ secrets.DOCKERHUB_APP }} || true
            docker run -d \
              --name ${{ secrets.DOCKERHUB_APP }} \
              --env-file /root/app/.env \
              -p 8080:8080 \
              ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_APP }}:latest